spring:
  datasource:
    url: jdbc:mysql://121.36.33.154:30000/renren_fast_quartz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    io.renren: debug