server:
  port: 1000
  servlet:
    context-path: /renren-fast

spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0