#设置服务端口
server:
  port: 9010

#设置eureka服务的名称
spring:
  application:
    name: eureka-server

#eureka配置
eureka:
  client:
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      defaultZone: http://127.0.0.1:9010/eureka
    #不注册自己
    register-with-eureka: false
    #不拉取服务
    fetch-registry: false