spring:
  profiles:
    active: dev
renren:
  jwt:
    # 加密秘钥（一定不能泄漏）
    secret: f4e2e52034348f86b67cde581c0f9eb5[cn.yuanyu.com]
    # token有效时长，7天（单位秒）
    expire: 604800
    header: token
server:
  port: 6969
logging:
  level:
    io.renren: debug