spring:
  datasource:
    url: jdbc:mysql://121.36.33.154:6000/tx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 6969
logging:
  level:
    cn.yuanyu.tx: debug