spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    order:
      url: jdbc:mysql://120.25.216.234:33006/order_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      url: jdbc:mysql://120.25.216.234:33006/user_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    com.yuanyu.multids: debug