spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      write: # 主数据源
        url: jdbc:mysql://120.25.216.234:33060/easycode_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      read: # 从数据源
        url: jdbc:mysql://121.36.33.154:33000/easycode_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: tms_select
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 6969

logging:
  level:
    cn.yuanyu.multids: debug
