spring:
  application:
    name: mp-boot
  datasource:
    url: jdbc:mysql://121.36.33.154:33600/mp?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    cn.yuanyu.mp.mapper: debug